name = "CMakeWrapper"
uuid = "d5fb7624-851a-54ee-a528-d3f3bac0b4a0"
authors = ["Robin Deits <robin.deits@gmail.com>"]
version = "0.2.3"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
CMake = "631607c0-34d2-5d66-819e-eb0f9aa2061a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BinDeps = "≥ 0.4.0"
Parameters = "≥ 0.5.0"
julia = "≥ 0.7.0"
